# Generated by Django 4.1.2 on 2022-12-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_updatenote_delete_samplemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BR', 'Bug Report'), ('FR', 'Feature Request'), ('IS', 'Improvement Suggestion'), ('RA', 'Request Assistance'), ('IR', 'ITC Recruitment'), ('OT', 'Others')], max_length=2)),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('resolved', models.BooleanField(default=False)),
                ('response', models.TextField()),
            ],
        ),
    ]
