# Generated by Django 4.1.2 on 2022-12-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_feedbackform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
