# Generated by Django 4.1.2 on 2023-01-25 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_feedbackform_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatenote',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='updatenote',
            name='added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
