# Generated by Django 4.1.2 on 2023-01-26 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_updatenote_public_alter_updatenote_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updatenote',
            options={},
        ),
        migrations.AlterField(
            model_name='updatenote',
            name='added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
