# Generated by Django 4.1.2 on 2023-01-26 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_updatenote_options_alter_updatenote_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatenote',
            name='added',
            field=models.DateField(default=datetime.datetime(2023, 1, 26, 4, 17, 42, 1980, tzinfo=datetime.timezone.utc)),
        ),
    ]
