# Generated by Django 4.1.2 on 2023-01-26 04:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_updatenote_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatenote',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
