# Generated by Django 4.1.2 on 2023-04-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0009_alter_updatenote_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackform",
            name="type",
            field=models.CharField(
                choices=[
                    ("Bug Report", "Bug Report"),
                    ("Feature Request", "Feature Request"),
                    ("Improvement Suggestion", "Improvement Suggestion"),
                    ("Request Assistance", "Request Assistance"),
                    ("ITC Recruitment", "ITC Recruitment"),
                    ("Others", "Others"),
                ],
                max_length=30,
            ),
        ),
    ]
