# Generated by Django 5.0.4 on 2024-06-17 09:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0010_alter_feedbackform_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackform",
            name="acknowledged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="feedbackform",
            name="time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
