# Generated by Django 4.1.13 on 2023-12-11 09:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modsoptimizer.utils.validation


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "academic_units",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("datetime_added", models.DateTimeField(auto_now_add=True)),
                (
                    "exam_schedule",
                    models.CharField(
                        blank=True,
                        max_length=53,
                        validators=[
                            modsoptimizer.utils.validation.validate_exam_schedule
                        ],
                    ),
                ),
                (
                    "common_schedule",
                    models.CharField(
                        max_length=192,
                        validators=[
                            modsoptimizer.utils.validation.validate_weekly_schedule
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Course Codes",
            },
        ),
        migrations.CreateModel(
            name="CourseIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index",
                    models.CharField(
                        max_length=5,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_format",
                                message="The value must be 5 numeric digits.",
                                regex="^\\d{5}$",
                            )
                        ],
                    ),
                ),
                ("information", models.TextField()),
                (
                    "schedule",
                    models.CharField(
                        max_length=192,
                        validators=[
                            modsoptimizer.utils.validation.validate_weekly_schedule
                        ],
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indexes",
                        to="modsoptimizer.coursecode",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Course Indexes",
            },
        ),
    ]
