# Generated by Django 4.1.13 on 2023-12-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modsoptimizer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecode",
            name="common_information",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="courseindex",
            name="filtered_information",
            field=models.TextField(blank=True, null=True),
        ),
    ]
