# Generated by Django 4.1.13 on 2024-01-02 15:02

from django.db import migrations, models
import modsoptimizer.utils.validation


class Migration(migrations.Migration):

    dependencies = [
        ("modsoptimizer", "0002_coursecode_common_information_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecode",
            name="common_information",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[modsoptimizer.utils.validation.validate_information],
            ),
        ),
        migrations.AlterField(
            model_name="courseindex",
            name="filtered_information",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[modsoptimizer.utils.validation.validate_information],
            ),
        ),
        migrations.AlterField(
            model_name="courseindex",
            name="information",
            field=models.TextField(
                validators=[modsoptimizer.utils.validation.validate_information]
            ),
        ),
    ]
