# Generated by Django 5.0.4 on 2024-06-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modsoptimizer", "0003_alter_coursecode_common_information_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecode",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coursecode",
            name="mutually_exclusive",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coursecode",
            name="not_available",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coursecode",
            name="not_available_all",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coursecode",
            name="offered_as_bde",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="coursecode",
            name="offered_as_ue",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="coursecode",
            name="prerequisite",
            field=models.TextField(blank=True, null=True),
        ),
    ]
