# Generated by Django 5.0.4 on 2024-06-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "modsoptimizer",
            "0004_coursecode_description_coursecode_mutually_exclusive_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecode",
            name="mutually_exclusive",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="coursecode",
            name="not_available",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="coursecode",
            name="not_available_all",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="coursecode",
            name="prerequisite",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
