# Generated by Django 5.0.4 on 2024-06-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modsoptimizer", "0005_alter_coursecode_mutually_exclusive_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecode",
            name="department_maintaining",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="coursecode",
            name="grade_type",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="coursecode",
            name="not_offered_as_bde_ue_to",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="coursecode",
            name="not_offered_as_core_to",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="coursecode",
            name="not_offered_as_pe_to",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
