# Generated by Django 5.0.4 on 2024-06-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modsoptimizer", "0006_coursecode_department_maintaining_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, unique=True)),
                ("value", models.CharField(max_length=300, unique=True)),
                ("datetime_added", models.DateTimeField(auto_now_add=True)),
                (
                    "courses",
                    models.ManyToManyField(
                        related_name="programs", to="modsoptimizer.coursecode"
                    ),
                ),
            ],
        ),
    ]
