# Generated by Django 5.0.4 on 2024-06-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modsoptimizer", "0007_courseprogram"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courseprogram",
            options={"verbose_name_plural": "Course Programs"},
        ),
        migrations.AddField(
            model_name="coursecode",
            name="program_list",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
