# Generated by Django 5.0.4 on 2024-06-17 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modsoptimizer", "0008_alter_courseprogram_options_coursecode_program_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseprogram",
            name="year",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
    ]
