# Generated by Django 5.0.4 on 2024-06-19 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modsoptimizer", "0009_courseprogram_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseprogram",
            name="year",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
