# Generated by Django 5.0.4 on 2024-06-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modsoptimizer", "0010_alter_courseprogram_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecode",
            name="level",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="coursecode",
            name="program_code",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
