# Generated by Django 5.0.4 on 2024-06-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modsoptimizer", "0011_coursecode_level_coursecode_program_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCodeProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program_code", models.CharField(max_length=3, unique=True)),
            ],
        ),
    ]
