
'''
manually taken from https://wis.ntu.edu.sg/webexe/owa/aus_subj_cont.main
per 17/06/2024 data (may change in the future!)
'''

html_content = '''
<select name="r_course_yr" style="font-family: Arial;font-size: 10pt; height:35px" fdprocessedid="oapujx">
<option value="">---Select an Option---
</option><option value="ACC;;1;F">Accountancy Year 1
</option><option value="ACC;GA;1;F">Accountancy (GA) Year 1
</option><option value="ACC;GA;2;F">Accountancy (GA) Year 2
</option><option value="ACC;GA;3;F">Accountancy (GA) Year 3
</option><option value="ACC;GB;1;F">Accountancy (GB) Year 1
</option><option value="ACC;GB;2;F">Accountancy (GB) Year 2
</option><option value="ACC;GB;3;F">Accountancy (GB) Year 3
</option><option value="ADM;;1;F">Art, Design &amp; Media Year 1
</option><option value="ADM;DA;1;F">Art, Design &amp; Media (DA) Year 1
</option><option value="ADM;DA;2;F">Art, Design &amp; Media (DA) Year 2
</option><option value="ADM;DA;3;F">Art, Design &amp; Media (DA) Year 3
</option><option value="ADM;DA;4;F">Art, Design &amp; Media (DA) Year 4
</option><option value="ADM;MA;1;F">Art, Design &amp; Media (MA) Year 1
</option><option value="ADM;MA;2;F">Art, Design &amp; Media (MA) Year 2
</option><option value="ADM;MA;3;F">Art, Design &amp; Media (MA) Year 3
</option><option value="ADM;MA;4;F">Art, Design &amp; Media (MA) Year 4
</option><option value="AERO;;1;F">Aerospace Engineering Year 1
</option><option value="AERO;;2;F">Aerospace Engineering Year 2
</option><option value="AERO;;3;F">Aerospace Engineering Year 3
</option><option value="AERO;;4;F">Aerospace Engineering Year 4
</option><option value="BIE;;1;F">Bioengineering Year 1
</option><option value="BIE;;2;F">Bioengineering Year 2
</option><option value="BIE;;3;F">Bioengineering Year 3
</option><option value="BIE;;4;F">Bioengineering Year 4
</option><option value="BMS;;1;F">Biomedical Sciences Year 1
</option><option value="BMS;;2;F">Biomedical Sciences Year 2
</option><option value="BMS;;3;F">Biomedical Sciences Year 3
</option><option value="BMS;;4;F">Biomedical Sciences Year 4
</option><option value="BS;;1;F">Biological Sciences Year 1
</option><option value="BS;;2;F">Biological Sciences Year 2
</option><option value="BS;;3;F">Biological Sciences Year 3
</option><option value="BS;;4;F">Biological Sciences Year 4
</option><option value="BSB;;1;F">Biomedical Sciences And Biobusiness Year 1
</option><option value="BSB;;2;F">Biomedical Sciences And Biobusiness Year 2
</option><option value="BSB;;3;F">Biomedical Sciences And Biobusiness Year 3
</option><option value="BSB;;4;F">Biomedical Sciences And Biobusiness Year 4
</option><option value="BSPY;;1;F">Biological Sciences And Psychology Year 1
</option><option value="BSPY;;2;F">Biological Sciences And Psychology Year 2
</option><option value="BSPY;;3;F">Biological Sciences And Psychology Year 3
</option><option value="BSPY;;4;F">Biological Sciences And Psychology Year 4
</option><option value="BUS;;1;F">Business Year 1
</option><option value="BUS;;2;F">Business Year 2
</option><option value="BUS;ACS;1;F">Business (ACS) Year 1
</option><option value="BUS;ACS;2;F">Business (ACS) Year 2
</option><option value="BUS;ACS;3;F">Business (ACS) Year 3
</option><option value="BUS;AWM;2;F">Business (AWM) Year 2
</option><option value="BUS;AWM;3;F">Business (AWM) Year 3
</option><option value="BUS;BA;1;F">Business (BA) Year 1
</option><option value="BUS;BA;2;F">Business (BA) Year 2
</option><option value="BUS;BA;3;F">Business (BA) Year 3
</option><option value="BUS;BAF;1;F">Business (BAF) Year 1
</option><option value="BUS;BAF;2;F">Business (BAF) Year 2
</option><option value="BUS;BAF;3;F">Business (BAF) Year 3
</option><option value="BUS;GA;1;F">Business (GA) Year 1
</option><option value="BUS;GA;2;F">Business (GA) Year 2
</option><option value="BUS;GB;1;F">Business (GB) Year 1
</option><option value="BUS;GB;2;F">Business (GB) Year 2
</option><option value="BUS;HRC;1;F">Business (HRC) Year 1
</option><option value="BUS;HRC;2;F">Business (HRC) Year 2
</option><option value="BUS;HRC;3;F">Business (HRC) Year 3
</option><option value="BUS;ITT;1;F">Business (ITT) Year 1
</option><option value="BUS;ITT;2;F">Business (ITT) Year 2
</option><option value="BUS;ITT;3;F">Business (ITT) Year 3
</option><option value="BUS;MKG;1;F">Business (MKG) Year 1
</option><option value="BUS;MKG;2;F">Business (MKG) Year 2
</option><option value="BUS;MKG;3;F">Business (MKG) Year 3
</option><option value="BUS;PBL;2;F">Business (PBL) Year 2
</option><option value="BUS;PBL;3;F">Business (PBL) Year 3
</option><option value="BUS;RA;1;F">Business (RA) Year 1
</option><option value="BUS;RA;2;F">Business (RA) Year 2
</option><option value="BUS;RA;3;F">Business (RA) Year 3
</option><option value="BUS;RMI;2;F">Business (RMI) Year 2
</option><option value="BUS;RMI;3;F">Business (RMI) Year 3
</option><option value="CBE;;1;F">Chemical &amp; Biomolecular Engineering Year 1
</option><option value="CBE;;2;F">Chemical &amp; Biomolecular Engineering Year 2
</option><option value="CBE;;3;F">Chemical &amp; Biomolecular Engineering Year 3
</option><option value="CBE;;4;F">Chemical &amp; Biomolecular Engineering Year 4
</option><option value="CE;;1;F">Computer Engineering Year 1
</option><option value="CE;;2;F">Computer Engineering Year 2
</option><option value="CE;;3;F">Computer Engineering Year 3
</option><option value="CE;;4;F">Computer Engineering Year 4
</option><option value="CEE;;2;F">Civil Engineering Year 2
</option><option value="CEE;;3;F">Civil Engineering Year 3
</option><option value="CEE;;4;F">Civil Engineering Year 4
</option><option value="CHEM;;1;F">Chemistry and Biological Chemistry Year 1
</option><option value="CHEM;;2;F">Chemistry and Biological Chemistry Year 2
</option><option value="CHEM;;3;F">Chemistry and Biological Chemistry Year 3
</option><option value="CHEM;;4;F">Chemistry and Biological Chemistry Year 4
</option><option value="CHIN;;1;F">Chinese Year 1
</option><option value="CHIN;;2;F">Chinese Year 2
</option><option value="CHIN;;3;F">Chinese Year 3
</option><option value="CHIN;;4;F">Chinese Year 4
</option><option value="CNEL;;1;F">Chinese And English Year 1
</option><option value="CNEL;;2;F">Chinese And English Year 2
</option><option value="CNEL;;3;F">Chinese And English Year 3
</option><option value="CNEL;;4;F">Chinese And English Year 4
</option><option value="CNLM;;1;F">Chinese And Linguistics &amp; Multilingual Studies Year 1
</option><option value="CNLM;;2;F">Chinese And Linguistics &amp; Multilingual Studies Year 2
</option><option value="CNLM;;3;F">Chinese And Linguistics &amp; Multilingual Studies Year 3
</option><option value="CNLM;;4;F">Chinese And Linguistics &amp; Multilingual Studies Year 4
</option><option value="CS;;1;F">Communication Studies Year 1
</option><option value="CS;;2;F">Communication Studies Year 2
</option><option value="CS;;3;F">Communication Studies Year 3
</option><option value="CS;;4;F">Communication Studies Year 4
</option><option value="CSC;;1;F">Computer Science Year 1
</option><option value="CSC;;2;F">Computer Science Year 2
</option><option value="CSC;;3;F">Computer Science Year 3
</option><option value="CSC;;4;F">Computer Science Year 4
</option><option value="DSAI;;1;F">Data Science &amp; Artificial Intelligence Year 1
</option><option value="DSAI;;2;F">Data Science &amp; Artificial Intelligence Year 2
</option><option value="DSAI;;3;F">Data Science &amp; Artificial Intelligence Year 3
</option><option value="DSAI;;4;F">Data Science &amp; Artificial Intelligence Year 4
</option><option value="ECDS;;1;F">Economics &amp; Data Science Year 1
</option><option value="ECDS;;2;F">Economics &amp; Data Science Year 2
</option><option value="ECDS;;3;F">Economics &amp; Data Science Year 3
</option><option value="ECDS;;4;F">Economics &amp; Data Science Year 4
</option><option value="ECMA;;1;F">Economics And Media Analytics Year 1
</option><option value="ECMA;;2;F">Economics And Media Analytics Year 2
</option><option value="ECMA;;3;F">Economics And Media Analytics Year 3
</option><option value="ECMA;;4;F">Economics And Media Analytics Year 4
</option><option value="ECON;;1;F">Economics Year 1
</option><option value="ECON;;2;F">Economics Year 2
</option><option value="ECON;;3;F">Economics Year 3
</option><option value="ECON;;4;F">Economics Year 4
</option><option value="ECPP;;1;F">Economics And Public Policy &amp; Global Affairs Year 1
</option><option value="ECPP;;2;F">Economics And Public Policy &amp; Global Affairs Year 2
</option><option value="ECPP;;3;F">Economics And Public Policy &amp; Global Affairs Year 3
</option><option value="ECPP;;4;F">Economics And Public Policy &amp; Global Affairs Year 4
</option><option value="ECPS;;1;F">Economics And Psychology Year 1
</option><option value="ECPS;;2;F">Economics And Psychology Year 2
</option><option value="ECPS;;3;F">Economics And Psychology Year 3
</option><option value="ECPS;;4;F">Economics And Psychology Year 4
</option><option value="EEE;;2;F">Electrical &amp; Electronic Engineering Year 2
</option><option value="EEE;;3;F">Electrical &amp; Electronic Engineering Year 3
</option><option value="EEE;;4;F">Electrical &amp; Electronic Engineering Year 4
</option><option value="EESS;;1;F">Environmental Earth Systems Science Year 1
</option><option value="EESS;;2;F">Environmental Earth Systems Science Year 2
</option><option value="EESS;ECO;2;F">Environmental Earth Systems Science (ECO) Year 2
</option><option value="EESS;ECO;3;F">Environmental Earth Systems Science (ECO) Year 3
</option><option value="EESS;ECO;4;F">Environmental Earth Systems Science (ECO) Year 4
</option><option value="EESS;GEO;3;F">Environmental Earth Systems Science (GEO) Year 3
</option><option value="EESS;GEOS;2;F">Environmental Earth Systems Science (GEOS) Year 2
</option><option value="EESS;GEOS;3;F">Environmental Earth Systems Science (GEOS) Year 3
</option><option value="EESS;GEOS;4;F">Environmental Earth Systems Science (GEOS) Year 4
</option><option value="EESS;SOES;2;F">Environmental Earth Systems Science (SOES) Year 2
</option><option value="EESS;SOES;3;F">Environmental Earth Systems Science (SOES) Year 3
</option><option value="EESS;SOES;4;F">Environmental Earth Systems Science (SOES) Year 4
</option><option value="ELAH;;1;F">English Literature And Art History Year 1
</option><option value="ELAH;;2;F">English Literature And Art History Year 2
</option><option value="ELAH;;3;F">English Literature And Art History Year 3
</option><option value="ELAH;;4;F">English Literature And Art History Year 4
</option><option value="ELH;;1;F">English Year 1
</option><option value="ELH;;2;F">English Year 2
</option><option value="ELH;;3;F">English Year 3
</option><option value="ELH;;4;F">English Year 4
</option><option value="ELHS;;1;F">English And History Year 1
</option><option value="ELHS;;2;F">English And History Year 2
</option><option value="ELHS;;3;F">English And History Year 3
</option><option value="ELHS;;4;F">English And History Year 4
</option><option value="ELPL;;1;F">English And Philosophy Year 1
</option><option value="ELPL;;2;F">English And Philosophy Year 2
</option><option value="ELPL;;3;F">English And Philosophy Year 3
</option><option value="ELPL;;4;F">English And Philosophy Year 4
</option><option value="ENE;;2;F">Environmental Engineering Year 2
</option><option value="ENE;;3;F">Environmental Engineering Year 3
</option><option value="ENE;;4;F">Environmental Engineering Year 4
</option><option value="ENG;;1;F">Engineering Year 1
</option><option value="ENG;CEE;1;F">Engineering (CEE) Year 1
</option><option value="ENG;EEE;1;F">Engineering (EEE) Year 1
</option><option value="ENG;ENE;1;F">Engineering (ENE) Year 1
</option><option value="ENG;ME;1;F">Engineering (ME) Year 1
</option><option value="ESPP;;1;F">Environmental Earth Systems Science And Public Policy &amp; Global Affairs Year 1
</option><option value="ESPP;;2;F">Environmental Earth Systems Science And Public Policy &amp; Global Affairs Year 2
</option><option value="ESPP;;3;F">Environmental Earth Systems Science And Public Policy &amp; Global Affairs Year 3
</option><option value="ESPP;;4;F">Environmental Earth Systems Science And Public Policy &amp; Global Affairs Year 4
</option><option value="HIST;;1;F">History Year 1
</option><option value="HIST;;2;F">History Year 2
</option><option value="HIST;;3;F">History Year 3
</option><option value="HIST;;4;F">History Year 4
</option><option value="HSCN;;1;F">History And Chinese Year 1
</option><option value="HSCN;;2;F">History And Chinese Year 2
</option><option value="HSCN;;3;F">History And Chinese Year 3
</option><option value="HSCN;;4;F">History And Chinese Year 4
</option><option value="HSLM;;1;F">History And Linguistics &amp; Multilingual Studies Year 1
</option><option value="HSLM;;2;F">History And Linguistics &amp; Multilingual Studies Year 2
</option><option value="HSLM;;3;F">History And Linguistics &amp; Multilingual Studies Year 3
</option><option value="HSLM;;4;F">History And Linguistics &amp; Multilingual Studies Year 4
</option><option value="IEM;;1;F">Information Engineering &amp; Media Year 1
</option><option value="IEM;;2;F">Information Engineering &amp; Media Year 2
</option><option value="IEM;;3;F">Information Engineering &amp; Media Year 3
</option><option value="IEM;;4;F">Information Engineering &amp; Media Year 4
</option><option value="LMEL;;1;F">Linguistics &amp; Multilingual Studies And English Year 1
</option><option value="LMEL;;2;F">Linguistics &amp; Multilingual Studies And English Year 2
</option><option value="LMEL;;3;F">Linguistics &amp; Multilingual Studies And English Year 3
</option><option value="LMEL;;4;F">Linguistics &amp; Multilingual Studies And English Year 4
</option><option value="LMPL;;1;F">Linguistics &amp; Multilingual Studies And Philosophy Year 1
</option><option value="LMPL;;2;F">Linguistics &amp; Multilingual Studies And Philosophy Year 2
</option><option value="LMPL;;3;F">Linguistics &amp; Multilingual Studies And Philosophy Year 3
</option><option value="LMPL;;4;F">Linguistics &amp; Multilingual Studies And Philosophy Year 4
</option><option value="LMS;;1;F">Linguistics &amp; Multilingual Studies Year 1
</option><option value="LMS;;2;F">Linguistics &amp; Multilingual Studies Year 2
</option><option value="LMS;;3;F">Linguistics &amp; Multilingual Studies Year 3
</option><option value="LMS;;4;F">Linguistics &amp; Multilingual Studies Year 4
</option><option value="MACS;;1;F">Mathematical And Computer Sciences Year 1
</option><option value="MACS;;2;F">Mathematical And Computer Sciences Year 2
</option><option value="MACS;;3;F">Mathematical And Computer Sciences Year 3
</option><option value="MACS;;4;F">Mathematical And Computer Sciences Year 4
</option><option value="MAEC;;1;F">Mathematics &amp; Economics Year 1
</option><option value="MAEC;;2;F">Mathematics &amp; Economics Year 2
</option><option value="MAEC;;3;F">Mathematics &amp; Economics Year 3
</option><option value="MAEC;;4;F">Mathematics &amp; Economics Year 4
</option><option value="MAEC;AMAS;2;F">Mathematics &amp; Economics (AMAS) Year 2
</option><option value="MAEO;;1;F">Mathematical Sciences And Economics Year 1
</option><option value="MAEO;;2;F">Mathematical Sciences And Economics Year 2
</option><option value="MAEO;;3;F">Mathematical Sciences And Economics Year 3
</option><option value="MAEO;;4;F">Mathematical Sciences And Economics Year 4
</option><option value="MAEO;AMAS;2;F">Mathematical Sciences And Economics (AMAS) Year 2
</option><option value="MAEO;AMAS;3;F">Mathematical Sciences And Economics (AMAS) Year 3
</option><option value="MAEO;AMAS;4;F">Mathematical Sciences And Economics (AMAS) Year 4
</option><option value="MAEO;BA;2;F">Mathematical Sciences And Economics (BA) Year 2
</option><option value="MAEO;BA;3;F">Mathematical Sciences And Economics (BA) Year 3
</option><option value="MAEO;BA;4;F">Mathematical Sciences And Economics (BA) Year 4
</option><option value="MAEO;PMAS;2;F">Mathematical Sciences And Economics (PMAS) Year 2
</option><option value="MAEO;PMAS;3;F">Mathematical Sciences And Economics (PMAS) Year 3
</option><option value="MAEO;PMAS;4;F">Mathematical Sciences And Economics (PMAS) Year 4
</option><option value="MAEO;STAT;2;F">Mathematical Sciences And Economics (STAT) Year 2
</option><option value="MAEO;STAT;3;F">Mathematical Sciences And Economics (STAT) Year 3
</option><option value="MAEO;STAT;4;F">Mathematical Sciences And Economics (STAT) Year 4
</option><option value="MAT;;1;F">Materials Engineering Year 1
</option><option value="MAT;;2;F">Materials Engineering Year 2
</option><option value="MAT;;3;F">Materials Engineering Year 3
</option><option value="MAT;;4;F">Materials Engineering Year 4
</option><option value="MATH;;1;F">Mathematical Sciences Year 1
</option><option value="MATH;;2;F">Mathematical Sciences Year 2
</option><option value="MATH;;3;F">Mathematical Sciences Year 3
</option><option value="MATH;;4;F">Mathematical Sciences Year 4
</option><option value="MATH;AMAS;1;F">Mathematical Sciences (AMAS) Year 1
</option><option value="MATH;AMAS;2;F">Mathematical Sciences (AMAS) Year 2
</option><option value="MATH;AMAS;3;F">Mathematical Sciences (AMAS) Year 3
</option><option value="MATH;AMAS;4;F">Mathematical Sciences (AMAS) Year 4
</option><option value="MATH;BA;1;F">Mathematical Sciences (BA) Year 1
</option><option value="MATH;BA;2;F">Mathematical Sciences (BA) Year 2
</option><option value="MATH;BA;3;F">Mathematical Sciences (BA) Year 3
</option><option value="MATH;BA;4;F">Mathematical Sciences (BA) Year 4
</option><option value="MATH;PMAS;1;F">Mathematical Sciences (PMAS) Year 1
</option><option value="MATH;PMAS;2;F">Mathematical Sciences (PMAS) Year 2
</option><option value="MATH;PMAS;3;F">Mathematical Sciences (PMAS) Year 3
</option><option value="MATH;PMAS;4;F">Mathematical Sciences (PMAS) Year 4
</option><option value="MATH;STAT;1;F">Mathematical Sciences (STAT) Year 1
</option><option value="MATH;STAT;2;F">Mathematical Sciences (STAT) Year 2
</option><option value="MATH;STAT;3;F">Mathematical Sciences (STAT) Year 3
</option><option value="MATH;STAT;4;F">Mathematical Sciences (STAT) Year 4
</option><option value="ME;;2;F">Mechanical Engineering Year 2
</option><option value="ME;;3;F">Mechanical Engineering Year 3
</option><option value="ME;;4;F">Mechanical Engineering Year 4
</option><option value="ME;DES;2;F">Mechanical Engineering (DES) Year 2
</option><option value="ME;DES;3;F">Mechanical Engineering (DES) Year 3
</option><option value="ME;DES;4;F">Mechanical Engineering (DES) Year 4
</option><option value="ME;RMS;2;F">Mechanical Engineering (RMS) Year 2
</option><option value="ME;RMS;3;F">Mechanical Engineering (RMS) Year 3
</option><option value="ME;RMS;4;F">Mechanical Engineering (RMS) Year 4
</option><option value="MS;;1;F">Maritime Studies Year 1
</option><option value="MS;;2;F">Maritime Studies Year 2
</option><option value="MS;;3;F">Maritime Studies Year 3
</option><option value="MS;;4;F">Maritime Studies Year 4
</option><option value="MS;ITG;1;F">Maritime Studies (ITG) Year 1
</option><option value="MS;ITG;2;F">Maritime Studies (ITG) Year 2
</option><option value="MS;ITG;3;F">Maritime Studies (ITG) Year 3
</option><option value="MS;ITG;4;F">Maritime Studies (ITG) Year 4
</option><option value="MS;MSB;1;F">Maritime Studies (MSB) Year 1
</option><option value="MS;MSB;2;F">Maritime Studies (MSB) Year 2
</option><option value="MS;MSB;3;F">Maritime Studies (MSB) Year 3
</option><option value="MS;MSB;4;F">Maritime Studies (MSB) Year 4
</option><option value="PHIL;;1;F">Philosophy Year 1
</option><option value="PHIL;;2;F">Philosophy Year 2
</option><option value="PHIL;;3;F">Philosophy Year 3
</option><option value="PHIL;;4;F">Philosophy Year 4
</option><option value="PHMS;;1;F">Physics And Mathematical Sciences Year 1
</option><option value="PHMS;;2;F">Physics And Mathematical Sciences Year 2
</option><option value="PHMS;;3;F">Physics And Mathematical Sciences Year 3
</option><option value="PHMS;;4;F">Physics And Mathematical Sciences Year 4
</option><option value="PHY;;1;F">Physics and Applied Physics Year 1
</option><option value="PHY;;2;F">Physics and Applied Physics Year 2
</option><option value="PHY;APHY;1;F">Physics and Applied Physics (APHY) Year 1
</option><option value="PHY;APHY;2;F">Physics and Applied Physics (APHY) Year 2
</option><option value="PHY;APHY;3;F">Physics and Applied Physics (APHY) Year 3
</option><option value="PHY;APHY;4;F">Physics and Applied Physics (APHY) Year 4
</option><option value="PHY;PPHY;1;F">Physics and Applied Physics (PPHY) Year 1
</option><option value="PHY;PPHY;2;F">Physics and Applied Physics (PPHY) Year 2
</option><option value="PHY;PPHY;3;F">Physics and Applied Physics (PPHY) Year 3
</option><option value="PHY;PPHY;4;F">Physics and Applied Physics (PPHY) Year 4
</option><option value="PLCN;;1;F">Philosophy And Chinese Year 1
</option><option value="PLCN;;2;F">Philosophy And Chinese Year 2
</option><option value="PLCN;;3;F">Philosophy And Chinese Year 3
</option><option value="PLCN;;4;F">Philosophy And Chinese Year 4
</option><option value="PLHS;;1;F">Philosophy And History Year 1
</option><option value="PLHS;;2;F">Philosophy And History Year 2
</option><option value="PLHS;;3;F">Philosophy And History Year 3
</option><option value="PLHS;;4;F">Philosophy And History Year 4
</option><option value="PPGA;;1;F">Public Policy And Global Affairs Year 1
</option><option value="PPGA;;2;F">Public Policy And Global Affairs Year 2
</option><option value="PPGA;;3;F">Public Policy And Global Affairs Year 3
</option><option value="PPGA;;4;F">Public Policy And Global Affairs Year 4
</option><option value="PSLM;;1;F">Psychology And Linguistics &amp; Multilingual Studies Year 1
</option><option value="PSLM;;2;F">Psychology And Linguistics &amp; Multilingual Studies Year 2
</option><option value="PSLM;;3;F">Psychology And Linguistics &amp; Multilingual Studies Year 3
</option><option value="PSLM;;4;F">Psychology And Linguistics &amp; Multilingual Studies Year 4
</option><option value="PSMA;;1;F">Psychology And Media Analytics Year 1
</option><option value="PSMA;;2;F">Psychology And Media Analytics Year 2
</option><option value="PSMA;;3;F">Psychology And Media Analytics Year 3
</option><option value="PSMA;;4;F">Psychology And Media Analytics Year 4
</option><option value="PSY;;1;F">Psychology Year 1
</option><option value="PSY;;2;F">Psychology Year 2
</option><option value="PSY;;3;F">Psychology Year 3
</option><option value="PSY;;4;F">Psychology Year 4
</option><option value="REP;;1;F">Renaissance Engineering Year 1
</option><option value="REP;ASEN;2;F">Renaissance Engineering (ASEN) Year 2
</option><option value="REP;ASEN;3;F">Renaissance Engineering (ASEN) Year 3
</option><option value="REP;ASEN;4;F">Renaissance Engineering (ASEN) Year 4
</option><option value="REP;BIE;2;F">Renaissance Engineering (BIE) Year 2
</option><option value="REP;BIE;3;F">Renaissance Engineering (BIE) Year 3
</option><option value="REP;BIE;4;F">Renaissance Engineering (BIE) Year 4
</option><option value="REP;CBE;2;F">Renaissance Engineering (CBE) Year 2
</option><option value="REP;CBE;3;F">Renaissance Engineering (CBE) Year 3
</option><option value="REP;CBE;4;F">Renaissance Engineering (CBE) Year 4
</option><option value="REP;CE;2;F">Renaissance Engineering (CE) Year 2
</option><option value="REP;CE;3;F">Renaissance Engineering (CE) Year 3
</option><option value="REP;CE;4;F">Renaissance Engineering (CE) Year 4
</option><option value="REP;CSC;2;F">Renaissance Engineering (CSC) Year 2
</option><option value="REP;CSC;3;F">Renaissance Engineering (CSC) Year 3
</option><option value="REP;CSC;4;F">Renaissance Engineering (CSC) Year 4
</option><option value="REP;CVEN;2;F">Renaissance Engineering (CVEN) Year 2
</option><option value="REP;CVEN;3;F">Renaissance Engineering (CVEN) Year 3
</option><option value="REP;CVEN;4;F">Renaissance Engineering (CVEN) Year 4
</option><option value="REP;EEE;2;F">Renaissance Engineering (EEE) Year 2
</option><option value="REP;EEE;3;F">Renaissance Engineering (EEE) Year 3
</option><option value="REP;EEE;4;F">Renaissance Engineering (EEE) Year 4
</option><option value="REP;ENE;2;F">Renaissance Engineering (ENE) Year 2
</option><option value="REP;ENE;3;F">Renaissance Engineering (ENE) Year 3
</option><option value="REP;ENE;4;F">Renaissance Engineering (ENE) Year 4
</option><option value="REP;MAT;2;F">Renaissance Engineering (MAT) Year 2
</option><option value="REP;MAT;3;F">Renaissance Engineering (MAT) Year 3
</option><option value="REP;MAT;4;F">Renaissance Engineering (MAT) Year 4
</option><option value="REP;ME;2;F">Renaissance Engineering (ME) Year 2
</option><option value="REP;ME;3;F">Renaissance Engineering (ME) Year 3
</option><option value="REP;ME;4;F">Renaissance Engineering (ME) Year 4
</option><option value="SOC;;1;F">Sociology Year 1
</option><option value="SOC;;2;F">Sociology Year 2
</option><option value="SOC;;3;F">Sociology Year 3
</option><option value="SOC;;4;F">Sociology Year 4
</option><option value="SSM;;1;F">Sport Science And Management Year 1
</option><option value=""> 
</option><option value="">---Double Degree--- 
</option><option value="ACBS;ACS;2;F">Accountancy And Business (ACS) Year 2
</option><option value="ACBS;ACS;4;F">Accountancy And Business (ACS) Year 4
</option><option value="ACBS;AWM;2;F">Accountancy And Business (AWM) Year 2
</option><option value="ACBS;AWM;3;F">Accountancy And Business (AWM) Year 3
</option><option value="ACBS;AWM;4;F">Accountancy And Business (AWM) Year 4
</option><option value="ACBS;BA;2;F">Accountancy And Business (BA) Year 2
</option><option value="ACBS;BA;3;F">Accountancy And Business (BA) Year 3
</option><option value="ACBS;BA;4;F">Accountancy And Business (BA) Year 4
</option><option value="ACBS;BAF;2;F">Accountancy And Business (BAF) Year 2
</option><option value="ACBS;BAF;3;F">Accountancy And Business (BAF) Year 3
</option><option value="ACBS;BAF;4;F">Accountancy And Business (BAF) Year 4
</option><option value="ACBS;GA;1;F">Accountancy And Business (GA) Year 1
</option><option value="ACBS;GA;2;F">Accountancy And Business (GA) Year 2
</option><option value="ACBS;GA;3;F">Accountancy And Business (GA) Year 3
</option><option value="ACBS;GA;4;F">Accountancy And Business (GA) Year 4
</option><option value="ACBS;GB;1;F">Accountancy And Business (GB) Year 1
</option><option value="ACBS;GB;2;F">Accountancy And Business (GB) Year 2
</option><option value="ACBS;GB;3;F">Accountancy And Business (GB) Year 3
</option><option value="ACBS;GB;4;F">Accountancy And Business (GB) Year 4
</option><option value="ACBS;HRC;2;F">Accountancy And Business (HRC) Year 2
</option><option value="ACBS;HRC;3;F">Accountancy And Business (HRC) Year 3
</option><option value="ACBS;HRC;4;F">Accountancy And Business (HRC) Year 4
</option><option value="ACBS;ITT;2;F">Accountancy And Business (ITT) Year 2
</option><option value="ACBS;ITT;3;F">Accountancy And Business (ITT) Year 3
</option><option value="ACBS;ITT;4;F">Accountancy And Business (ITT) Year 4
</option><option value="ACBS;MKG;2;F">Accountancy And Business (MKG) Year 2
</option><option value="ACBS;MKG;3;F">Accountancy And Business (MKG) Year 3
</option><option value="ACBS;MKG;4;F">Accountancy And Business (MKG) Year 4
</option><option value="ACBS;PBL;2;F">Accountancy And Business (PBL) Year 2
</option><option value="ACBS;PBL;3;F">Accountancy And Business (PBL) Year 3
</option><option value="ACBS;PBL;4;F">Accountancy And Business (PBL) Year 4
</option><option value="ACBS;RA;2;F">Accountancy And Business (RA) Year 2
</option><option value="ACBS;RA;3;F">Accountancy And Business (RA) Year 3
</option><option value="ACBS;RA;4;F">Accountancy And Business (RA) Year 4
</option><option value="ACBS;RMI;2;F">Accountancy And Business (RMI) Year 2
</option><option value="ACBS;RMI;3;F">Accountancy And Business (RMI) Year 3
</option><option value="ACBS;RMI;4;F">Accountancy And Business (RMI) Year 4
</option><option value="ACDA;;1;F">Accountancy And Data Science &amp; Artificial Intelligence Year 1
</option><option value="ACDA;;2;F">Accountancy And Data Science &amp; Artificial Intelligence Year 2
</option><option value="ACDA;;3;F">Accountancy And Data Science &amp; Artificial Intelligence Year 3
</option><option value="ACDA;;4;F">Accountancy And Data Science &amp; Artificial Intelligence Year 4
</option><option value="ACDA;;5;F">Accountancy And Data Science &amp; Artificial Intelligence Year 5
</option><option value="ACDA;GA;1;F">Accountancy And Data Science &amp; Artificial Intelligence (GA) Year 1
</option><option value="ACDA;GA;2;F">Accountancy And Data Science &amp; Artificial Intelligence (GA) Year 2
</option><option value="ACDA;GB;1;F">Accountancy And Data Science &amp; Artificial Intelligence (GB) Year 1
</option><option value="ACDA;GB;2;F">Accountancy And Data Science &amp; Artificial Intelligence (GB) Year 2
</option><option value="ASEC;;1;F">Aerospace Engineering And Economics Year 1
</option><option value="ASEC;;2;F">Aerospace Engineering And Economics Year 2
</option><option value="ASEC;;3;F">Aerospace Engineering And Economics Year 3
</option><option value="ASEC;;4;F">Aerospace Engineering And Economics Year 4
</option><option value="ASEC;;5;F">Aerospace Engineering And Economics Year 5
</option><option value="BCE;;1;F">Business And Computer Engineering Year 1
</option><option value="BCE;;4;F">Business And Computer Engineering Year 4
</option><option value="BCG;;1;F">Business And Computing Year 1
</option><option value="BCG;;2;F">Business And Computing Year 2
</option><option value="BCG;;3;F">Business And Computing Year 3
</option><option value="BCG;;4;F">Business And Computing Year 4
</option><option value="BEEC;;1;F">Bioengineering And Economics Year 1
</option><option value="BEEC;;2;F">Bioengineering And Economics Year 2
</option><option value="BEEC;;3;F">Bioengineering And Economics Year 3
</option><option value="BEEC;;4;F">Bioengineering And Economics Year 4
</option><option value="BEEC;;5;F">Bioengineering And Economics Year 5
</option><option value="CBEC;;1;F">Chemical &amp; Biomolecular Engineering And Economics Year 1
</option><option value="CBEC;;2;F">Chemical &amp; Biomolecular Engineering And Economics Year 2
</option><option value="CBEC;;3;F">Chemical &amp; Biomolecular Engineering And Economics Year 3
</option><option value="CBEC;;4;F">Chemical &amp; Biomolecular Engineering And Economics Year 4
</option><option value="CBEC;;5;F">Chemical &amp; Biomolecular Engineering And Economics Year 5
</option><option value="CEEC;;1;F">Computer Engineering And Economics Year 1
</option><option value="CEEC;;2;F">Computer Engineering And Economics Year 2
</option><option value="CEEC;;3;F">Computer Engineering And Economics Year 3
</option><option value="CEEC;;4;F">Computer Engineering And Economics Year 4
</option><option value="CEEC;;5;F">Computer Engineering And Economics Year 5
</option><option value="CSEC;;1;F">Computer Science And Economics Year 1
</option><option value="CSEC;;2;F">Computer Science And Economics Year 2
</option><option value="CSEC;;3;F">Computer Science And Economics Year 3
</option><option value="CSEC;;4;F">Computer Science And Economics Year 4
</option><option value="CSEC;;5;F">Computer Science And Economics Year 5
</option><option value="CVEC;;1;F">Civil Engineering And Economics Year 1
</option><option value="CVEC;;2;F">Civil Engineering And Economics Year 2
</option><option value="CVEC;;3;F">Civil Engineering And Economics Year 3
</option><option value="CVEC;;4;F">Civil Engineering And Economics Year 4
</option><option value="CVEC;;5;F">Civil Engineering And Economics Year 5
</option><option value="EEEC;;1;F">Electrical &amp; Electronic Engineering And Economics Year 1
</option><option value="EEEC;;2;F">Electrical &amp; Electronic Engineering And Economics Year 2
</option><option value="EEEC;;3;F">Electrical &amp; Electronic Engineering And Economics Year 3
</option><option value="EEEC;;4;F">Electrical &amp; Electronic Engineering And Economics Year 4
</option><option value="ENEC;;1;F">Environmental Engineering And Economics Year 1
</option><option value="ENEC;;2;F">Environmental Engineering And Economics Year 2
</option><option value="ENEC;;3;F">Environmental Engineering And Economics Year 3
</option><option value="ENEC;;4;F">Environmental Engineering And Economics Year 4
</option><option value="ENEC;;5;F">Environmental Engineering And Economics Year 5
</option><option value="IEEC;;1;F">Information Engineering &amp; Media And Economics Year 1
</option><option value="IEEC;;2;F">Information Engineering &amp; Media And Economics Year 2
</option><option value="IEEC;;3;F">Information Engineering &amp; Media And Economics Year 3
</option><option value="IEEC;;4;F">Information Engineering &amp; Media And Economics Year 4
</option><option value="IEEC;;5;F">Information Engineering &amp; Media And Economics Year 5
</option><option value="MEEC;;1;F">Mechanical Engineering And Economics Year 1
</option><option value="MEEC;;2;F">Mechanical Engineering And Economics Year 2
</option><option value="MEEC;;3;F">Mechanical Engineering And Economics Year 3
</option><option value="MEEC;;4;F">Mechanical Engineering And Economics Year 4
</option><option value="MEEC;;5;F">Mechanical Engineering And Economics Year 5
</option><option value="MEEC;DES;1;F">Mechanical Engineering And Economics (DES) Year 1
</option><option value="MEEC;DES;2;F">Mechanical Engineering And Economics (DES) Year 2
</option><option value="MEEC;DES;3;F">Mechanical Engineering And Economics (DES) Year 3
</option><option value="MEEC;DES;4;F">Mechanical Engineering And Economics (DES) Year 4
</option><option value="MEEC;RMS;1;F">Mechanical Engineering And Economics (RMS) Year 1
</option><option value="MEEC;RMS;2;F">Mechanical Engineering And Economics (RMS) Year 2
</option><option value="MEEC;RMS;3;F">Mechanical Engineering And Economics (RMS) Year 3
</option><option value="MEEC;RMS;4;F">Mechanical Engineering And Economics (RMS) Year 4
</option><option value="MEEC;RMS;5;F">Mechanical Engineering And Economics (RMS) Year 5
</option><option value="MTEC;;1;F">Materials Engineering And Economics Year 1
</option><option value="MTEC;;2;F">Materials Engineering And Economics Year 2
</option><option value="MTEC;;3;F">Materials Engineering And Economics Year 3
</option><option value="MTEC;;4;F">Materials Engineering And Economics Year 4
</option><option value="MTEC;;5;F">Materials Engineering And Economics Year 5
</option><option value=""> 
</option><option value="MLOAD;AHIS;">Minor in Art History
</option><option value="MLOAD;APY;">Minor in Applied Physics
</option><option value="MLOAD;CCW;">Minor in Chinese Creative Writing
</option><option value="MLOAD;CDA;">Minor in Computing And Data Analysis
</option><option value="MLOAD;CHEM;">Minor in Chemistry And Biological Chemistry
</option><option value="MLOAD;CHIN;">Minor in Chinese
</option><option value="MLOAD;CM;">Minor in Computing
</option><option value="MLOAD;CS;">Minor in Communication Studies
</option><option value="MLOAD;CW;">Minor in Creative Writing
</option><option value="MLOAD;DDA;">Minor in Digitalisation And Data Analytics
</option><option value="MLOAD;DRA;">Minor in Drama And Performance
</option><option value="MLOAD;DST;">Minor in Design And Systems Thinking
</option><option value="MLOAD;ECHE;">Minor in Early Childhood Education
</option><option value="MLOAD;ECON;">Minor in Economics
</option><option value="MLOAD;EDU;">Minor in Education Studies
</option><option value="MLOAD;EH;">Minor in Environmental Humanities
</option><option value="MLOAD;ELIT;">Minor in English Literature
</option><option value="MLOAD;ENGY;">Minor in Energy
</option><option value="MLOAD;ENT;">Minor in Entrepreneurship
</option><option value="MLOAD;ENUS;">Minor in Environmental And Urban Studies
</option><option value="MLOAD;ENV;">Minor in Environmental Management
</option><option value="MLOAD;ENVS;">Minor in Environmental Sustainability
</option><option value="MLOAD;ES;">Minor in ES
</option><option value="MLOAD;ESH;">Minor in English Language
</option><option value="MLOAD;FIN;">Minor in Finance
</option><option value="MLOAD;FS;">Minor in Film
</option><option value="MLOAD;GA;">Minor in Global Asia
</option><option value="MLOAD;GD;">Minor in Gender And Diversity Studies
</option><option value="MLOAD;GUP;">Minor in Geography And Urban Planning
</option><option value="MLOAD;HES;">Minor in Health And Society
</option><option value="MLOAD;HIST;">Minor in History
</option><option value="MLOAD;ITG;">Minor in International Trading
</option><option value="MLOAD;LFSC;">Minor in Life Sciences
</option><option value="MLOAD;LING;">Minor in Linguistics And Multilingual Studies
</option><option value="MLOAD;MATH;">Minor in Mathematics
</option><option value="MLOAD;ML;">Minor in Modern Languages
</option><option value="MLOAD;MUS;">Minor in Music
</option><option value="MLOAD;NBS;">Minor in Business
</option><option value="MLOAD;PHIL;">Minor in Philosophy
</option><option value="MLOAD;PHO;">Minor in Photography
</option><option value="MLOAD;PHY;">Minor in Physics
</option><option value="MLOAD;PPGA;">Minor in Public Policy And Global Affairs
</option><option value="MLOAD;PSY;">Minor in Psychology
</option><option value="MLOAD;RA;">Minor in Risk Analytics
</option><option value="MLOAD;RMI;">Minor in Risk Management And Insurance
</option><option value="MLOAD;SC;">Minor in Strategic Communication
</option><option value="MLOAD;SNE;">Minor in Special Needs Education
</option><option value="MLOAD;SOC;">Minor in Sociology
</option><option value="MLOAD;SOL;">Minor in Science Of Learning
</option><option value="MLOAD;SSCI;">Minor in Sport Science
</option><option value="MLOAD;STS;">Minor in Science, Technology And Society
</option><option value="MLOAD;SUP;">Minor in Sustainable Urban Planning
</option><option value="MLOAD;SYMT;">Minor in Systems Management
</option><option value="MLOAD;TRAN;">Minor in Translation
</option><option value="MLOAD;YWG;">Minor in Youth Work And Guidance
</option><option value=""> 
</option><option value="GERP;AHSS;X;F">General Education in Art, Humanities and Social Sciences
</option><option value="GERP;BM;X;F">General Education in Business &amp; Management
</option><option value="GERP;STS;X;F">General Education in Science, Technology &amp; Society
</option><option value="GERP;LS;X;F">General Education in Liberal Studies
</option><option value="GERP;LA;X;F">General Education in Liberal Arts
</option><option value=""> 
</option><option value="CNY;CNY;X">C N Yang Scholars Programme
</option><option value=""> 
</option><option value="USP;CORE;X;F">University Scholars Programme (Core)
</option><option value="USP;SS;X;F">University Scholars Programme in Social Science
</option><option value="USP;AHC;X;F">University Scholars Programme in Arts, Humanities and Culture
</option><option value="USP;IS;X;F">University Scholars Programme in Interdisciplinary Studies
</option><option value="USP;SE;X;F">University Scholars Programme in Science and Engineering
</option><option value="USP;STS;X;F">University Scholars Programme in Science, Technology &amp; Society
</option><option value=""> 
</option><option value="">---All Broadening and Deepening/Unrestricted Electives---
</option><option value="GLOAD;ACC;X;F">Accountancy
</option><option value="GLOAD;ADM;X;F">Art, Design &amp; Media
</option><option value="GLOAD;BMS;X;F">Biomedical Sciences
</option><option value="GLOAD;BS;X;F">Biological Sciences
</option><option value="GLOAD;BUS;X;F">Business
</option><option value="GLOAD;CBE;X;F">Chemical &amp; Biomolecular Engineering
</option><option value="GLOAD;CE;X;F">Computer Engineering
</option><option value="GLOAD;CEE;X;F">Civil Engineering
</option><option value="GLOAD;CHEM;X;F">Chemistry and Biological Chemistry
</option><option value="GLOAD;CHIN;X;F">Chinese
</option><option value="GLOAD;CS;X;F">Communication Studies
</option><option value="GLOAD;CSC;X;F">Computer Science
</option><option value="GLOAD;ECON;X;F">Economics
</option><option value="GLOAD;EEE;X;F">Electrical &amp; Electronic Engineering
</option><option value="GLOAD;EESS;X;F">Environmental Earth Systems Science
</option><option value="GLOAD;ELH;X;F">English
</option><option value="GLOAD;HIST;X;F">History
</option><option value="GLOAD;ICC;X;F">Interdisciplinary Collaborative Courses
</option><option value="GLOAD;LMS;X;F">Linguistics &amp; Multilingual Studies
</option><option value="GLOAD;MAT;X;F">Materials Engineering
</option><option value="GLOAD;MATH;X;F">Mathematical Sciences
</option><option value="GLOAD;ME;X;F">Mechanical Engineering
</option><option value="GLOAD;MED;X;F">Medicine
</option><option value="GLOAD;MS;X;F">Maritime Studies
</option><option value="GLOAD;NIE;X;F">National Institute of Education
</option><option value="GLOAD;NTC;X;F">Nanyang Technopreneurship Centre
</option><option value="GLOAD;PHIL;X;F">Philosophy
</option><option value="GLOAD;PHY;X;F">Physics and Applied Physics
</option><option value="GLOAD;PPGA;X;F">Public Policy And Global Affairs
</option><option value="GLOAD;PSY;X;F">Psychology
</option><option value="GLOAD;SOC;X;F">Sociology
</option><option value="GLOAD;SOH;X;F">Humanities
</option><option value="GLOAD;SPS;X;F">Physical and Mathematical Sciences
</option><option value="GLOAD;SSM;X;F">Sport Science And Management
</option><option value="GLOAD;SSS;X;F">Social Sciences
</option></select>
'''
