# Generated by Django 4.1.2 on 2023-01-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufacility', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verification',
            old_name='role',
            new_name='hongen_name',
        ),
        migrations.RemoveField(
            model_name='ufacilityuser',
            name='status',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='email',
        ),
        migrations.AddField(
            model_name='verification',
            name='hongen_phone_number',
            field=models.CharField(default='hongen', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10),
            preserve_default=False,
        ),
    ]
