# Generated by Django 4.1.2 on 2022-12-19 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ufacility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ufacility.venue'),
        ),
    ]
