# Generated by Django 4.1.2 on 2023-01-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ufacility", "0002_booking2_delete_booking"),
        ("ufacility", "0002_rename_role_verification_hongen_name_and_more"),
    ]

    operations = []
