# Generated by Django 4.1.2 on 2023-01-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufacility', '0002_alter_booking_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='security_email',
            field=models.CharField(default='secrity@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
