# Generated by Django 4.1.2 on 2023-01-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ufacility", "0003_merge_20230128_1856"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ufacilityuser",
            name="role",
        ),
        migrations.AddField(
            model_name="ufacilityuser",
            name="hongen_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="ufacilityuser",
            name="hongen_phone_number",
            field=models.CharField(default="", max_length=100),
        ),
    ]
