# Generated by Django 4.1.2 on 2023-01-29 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "ufacility",
            "0004_remove_ufacilityuser_role_ufacilityuser_hongen_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="booking2",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booking2",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="booking2",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
