# Generated by Django 4.1.2 on 2023-01-30 12:06

from django.db import migrations, models
from ufacility.models import validate_singapore_phone_number


class Migration(migrations.Migration):

    dependencies = [
        ("ufacility", "0005_booking2_date_alter_booking2_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ufacilityuser",
            name="hongen_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ufacilityuser",
            name="hongen_phone_number",
            field=models.CharField(
                max_length=8,
                validators=[validate_singapore_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="verification",
            name="hongen_phone_number",
            field=models.CharField(
                max_length=8,
                validators=[validate_singapore_phone_number],
            ),
        ),
    ]
