# Generated by Django 4.1.2 on 2023-01-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ufacility", "0006_alter_ufacilityuser_hongen_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ufacilityuser",
            name="cca",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="ufacilityuser",
            name="hongen_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="verification",
            name="cca",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="verification",
            name="hongen_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="verification",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                ],
                max_length=8,
            ),
        ),
    ]
