# Generated by Django 4.1.2 on 2023-02-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ufacility", "0007_alter_ufacilityuser_cca_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="venue",
            name="security_email",
            field=models.EmailField(max_length=50),
        ),
    ]
