# Generated by Django 4.1.2 on 2023-02-01 12:30

from django.db import migrations, models
import ufacility.models


class Migration(migrations.Migration):

    dependencies = [
        ("ufacility", "0008_alter_venue_name_alter_venue_security_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking2",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to=ufacility.models.get_booking_path
            ),
        ),
    ]
