# Generated by Django 4.1.2 on 2023-02-15 14:44

from django.db import migrations, models
import django.db.models.deletion
import ufacility.models


class Migration(migrations.Migration):

    dependencies = [
        ("ufacility", "0009_booking2_attachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("purpose", models.CharField(max_length=200)),
                ("pax", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=ufacility.models.get_booking_path,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_data", models.DateField()),
                (
                    "recurring",
                    models.CharField(
                        choices=[
                            ("ALL", "Everyday"),
                            ("MON", "Monday"),
                            ("TUE", "Tuesday"),
                            ("WED", "Wednesday"),
                            ("THU", "Thursday"),
                            ("FRI", "Friday"),
                            ("SAT", "Saturday"),
                            ("SUN", "Sunday"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ufacility.ufacilityuser",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ufacility.venue",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
