# Generated by Django 4.1.2 on 2023-02-15 15:02

from django.db import migrations, models
import ufacility.models


class Migration(migrations.Migration):

    dependencies = [
        ("ufacility", "0010_bookinggroup"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookinggroup",
            old_name="end_data",
            new_name="end_date",
        ),
        migrations.AlterField(
            model_name="bookinggroup",
            name="attachment",
            field=models.FileField(
                null=True, upload_to=ufacility.models.get_booking_path
            ),
        ),
    ]
