# Generated by Django 4.1.2 on 2023-02-15 15:12

from django.db import migrations, models
import ufacility.models


class Migration(migrations.Migration):

    dependencies = [
        ("ufacility", "0011_rename_end_data_bookinggroup_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinggroup",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to=ufacility.models.get_booking_path
            ),
        ),
    ]
