# Generated by Django 4.1.2 on 2023-02-15 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ufacility", "0012_alter_bookinggroup_attachment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking2",
            name="attachment",
        ),
        migrations.AddField(
            model_name="bookinggroup",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 2, 15, 15, 24, 40, 572043, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
