# Generated by Django 4.1.2 on 2023-02-15 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ufacility", "0013_remove_booking2_attachment_bookinggroup_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking2",
            name="booking_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="ufacility.bookinggroup",
            ),
        ),
    ]
