# Generated by Django 4.1.2 on 2023-02-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ufacility", "0014_booking2_booking_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="venue",
            name="is_send_security_mail",
            field=models.BooleanField(default=True),
        ),
    ]
