# Generated by Django 4.1.2 on 2023-03-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ufacility", "0015_securityemail_venue_is_send_security_mail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="security_email",
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
