# Generated by Django 4.1.2 on 2023-04-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ufacility", "0016_alter_venue_security_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venue",
            name="security_email",
        ),
    ]
