# Generated by Django 4.1.2 on 2023-01-12 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sso', '0005_user_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAdmin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('allow_non_undergraduate', models.BooleanField(default=True)),
                ('allow_exchange_student', models.BooleanField(default=True)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('event_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventadmin')),
            ],
        ),
    ]
