# Generated by Django 4.1.2 on 2023-01-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_end_time_alter_event_event_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='auto_end',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='auto_start',
            field=models.BooleanField(default=True),
        ),
    ]
