# Generated by Django 4.1.2 on 2023-01-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_auto_end_event_auto_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=False),
        ),
        migrations.RenameField(
            model_name='event',
            old_name='is_active',
            new_name='_is_active',
        ),
    ]
