# Generated by Django 4.1.2 on 2023-01-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='_is_active',
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
