# Generated by Django 4.1.2 on 2023-01-26 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_event__is_active_event_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_active',
            new_name='_is_active',
        ),
    ]
