# Generated by Django 4.1.2 on 2023-01-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_event_admin'),
        ('event', '0006_rename_is_active_event__is_active'),
    ]

    operations = [
    ]
