# Generated by Django 4.1.7 on 2023-02-23 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_matriccheckin_eventofficer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventofficer',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='event.event'),
        ),
        migrations.AlterField(
            model_name='matriccheckin',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matric_checked_in', to='event.event'),
        ),
    ]
