# Generated by Django 4.1.7 on 2023-03-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_eventofficer_event_alter_matriccheckin_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='_is_active',
            new_name='set_is_active',
        ),
    ]
