# Generated by Django 4.1.7 on 2023-03-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_rename__is_active_event_set_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='set_is_active',
            new_name='is_active',
        ),
    ]
