# Generated by Django 4.1.7 on 2023-03-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_rename_set_is_active_event_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
