# Generated by Django 4.1.13 on 2025-03-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='itemloanrequest',
            options={'verbose_name': 'Item Loan Request', 'verbose_name_plural': 'Item Loan Requests'},
        ),
    ]
