# Generated by Django 4.1.13 on 2025-03-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_item_options_alter_itemloanrequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemloanrequest',
            name='approval_status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('returned', 'Returned')], default='processing', max_length=10),
        ),
    ]
