# Generated by Django 5.0.4 on 2024-04-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulocker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="locker",
            name="passcode",
            field=models.CharField(default="", max_length=10),
        ),
    ]
