# Generated by Django 4.1.13 on 2024-03-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulocker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locker",
            name="number",
        ),
        migrations.AddField(
            model_name="locker",
            name="name",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
    ]
