# Generated by Django 4.1.13 on 2024-03-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulocker", "0002_remove_locker_number_locker_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="payment_status",
        ),
        migrations.AddField(
            model_name="booking",
            name="command",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="locker",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="locker",
            name="passcode",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="booking",
            name="organization_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="position",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("withdrawn", "Withdrawn"),
                    ("rejected", "Rejected"),
                    ("approved - awaiting payment", "Approved - Awaiting Payment"),
                    (
                        "approved - awaiting verification",
                        "Approved - Awaiting Verification",
                    ),
                    ("allocated", "Allocated"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
