# Generated by Django 4.1.13 on 2024-03-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulocker", "0002_locker_passcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="command",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="end_month",
        ),
    ]