# Generated by Django 4.1.13 on 2024-03-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulocker', '0002_remove_locker_number_locker_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_month',
        ),
    ]
