# Generated by Django 4.1.13 on 2024-08-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulocker', '0002_locker_passcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='command',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_month',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=50),
        ),
    ]
