# Generated by Django 4.1.13 on 2024-03-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulocker", "0003_remove_booking_payment_status_booking_command_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ulockeradmin",
            options={
                "verbose_name": "ULocker Admin",
                "verbose_name_plural": "ULocker Admins",
            },
        ),
        migrations.RemoveField(
            model_name="booking",
            name="command",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="end_month",
        ),
        migrations.AddField(
            model_name="booking",
            name="comment",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
