# Generated by Django 4.1.13 on 2024-08-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulocker', '0003_booking_command_booking_end_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
