# Generated by Django 4.1.13 on 2024-03-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulocker", "0004_alter_ulockeradmin_options_remove_booking_command_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ulockeradmin",
            name="is_send_allocation_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="ulockeradmin",
            name="is_send_creation_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="ulockeradmin",
            name="is_send_verification_email",
            field=models.BooleanField(default=True),
        ),
    ]
