# Generated by Django 4.1.13 on 2024-08-08 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulocker', '0004_locker_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='command',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='locker',
            name='number',
        ),
    ]
