# Generated by Django 4.1.13 on 2024-03-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulocker", "0005_ulockeradmin_is_send_allocation_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ULockerConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monthly_price", models.CharField(max_length=20)),
                ("semesterly_price", models.CharField(max_length=20)),
                ("yearly_price", models.CharField(max_length=20)),
                ("qr_code_image", models.TextField()),
            ],
            options={
                "verbose_name": "ULocker Config",
                "verbose_name_plural": "ULocker Config",
            },
        ),
    ]
