# Generated by Django 4.1.2 on 2023-01-04 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('index', models.CharField(max_length=5, unique=True)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('information', models.TextField()),
                ('pending_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Course Indexes',
            },
        ),
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('S', 'Searching'), ('W', 'Waiting'), ('C', 'Completed')], default='S', max_length=1)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('datetime_found', models.DateTimeField(blank=True, null=True)),
                ('wanted_indexes', models.CharField(max_length=100)),
                ('current_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_swap', to='starswar.courseindex')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
