# Generated by Django 4.1.2 on 2023-01-04 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starswar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexSwapperConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_scraper_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='swaprequest',
            options={'verbose_name_plural': 'Swap Requests'},
        ),
        migrations.AddField(
            model_name='courseindex',
            name='academic_units',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
            preserve_default=False,
        ),
    ]
