# Generated by Django 4.1.2 on 2023-01-10 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starswar', '0002_indexswapperconfig_alter_swaprequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexswapperconfig',
            options={'verbose_name_plural': 'Index Swapper Configuration'},
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='current_index',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='available_swap', to='starswar.courseindex'),
        ),
    ]
