# Generated by Django 4.1.2 on 2023-08-05 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("starswar", "0003_alter_indexswapperconfig_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="XSwapRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_info", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("S", "Searching"),
                            ("W", "Waiting"),
                            ("C", "Completed"),
                        ],
                        default="S",
                        max_length=1,
                    ),
                ),
                ("datetime_added", models.DateTimeField(auto_now_add=True)),
                ("datetime_found", models.DateTimeField(blank=True, null=True)),
                ("wanted_indexes", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Swap Requests",
            },
        ),
        migrations.RenameModel(
            old_name="CourseIndex",
            new_name="XCourseIndex",
        ),
        migrations.DeleteModel(
            name="SwapRequest",
        ),
        migrations.AddField(
            model_name="xswaprequest",
            name="current_index",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Xavailable_swap",
                to="starswar.xcourseindex",
            ),
        ),
        migrations.AddField(
            model_name="xswaprequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Xswap_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
