# Generated by Django 4.1.2 on 2022-11-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0002_user_custom_token_user_token_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='custom_token',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
