# Generated by Django 4.1.2 on 2022-11-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0003_alter_user_custom_token_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='custom_token',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
