# Generated by Django 4.1.2 on 2022-11-01 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0004_user_display_name_alter_user_custom_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
