name: SU ITC Backend CI

on:
  workflow_dispatch:
    branches: [ 'main' ]
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          HOSTNAME: ${{ secrets.SSH_HOSTNAME }}
      
        run: |
          echo "Starting deployment"
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $USERNAME@$HOSTNAME "
            whoami &&
            cd ~/ntusu-itc-backend &&
            git pull -v &&
            sudo docker-compose up -d --build
            "

